// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1, 0}
}

// healthCheck proto
type HealthCheckRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

type UploadRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Record               string   `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	CliAddr              string   `protobuf:"bytes,4,opt,name=cliAddr,proto3" json:"cliAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UploadRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *UploadRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UploadRequest) GetCliAddr() string {
	if m != nil {
		return m.CliAddr
	}
	return ""
}

type UploadResponse struct {
	ErrorMsg             string   `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	ResponseCode         int32    `protobuf:"varint,2,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *UploadResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

type SearchRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SearchString         string   `protobuf:"bytes,2,opt,name=searchString,proto3" json:"searchString,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	CliAddr              string   `protobuf:"bytes,4,opt,name=cliAddr,proto3" json:"cliAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SearchRequest) GetSearchString() string {
	if m != nil {
		return m.SearchString
	}
	return ""
}

func (m *SearchRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SearchRequest) GetCliAddr() string {
	if m != nil {
		return m.CliAddr
	}
	return ""
}

type SearchResponse struct {
	Response             []string `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	ResponseCode         int32    `protobuf:"varint,2,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{5}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetResponse() []string {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SearchResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

type LoginRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CliAddr              string   `protobuf:"bytes,3,opt,name=cliAddr,proto3" json:"cliAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{6}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetCliAddr() string {
	if m != nil {
		return m.CliAddr
	}
	return ""
}

type LoginResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{7}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CliAddr              string   `protobuf:"bytes,2,opt,name=cliAddr,proto3" json:"cliAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{8}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LogoutRequest) GetCliAddr() string {
	if m != nil {
		return m.CliAddr
	}
	return ""
}

type LogoutResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{9}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

type CleanRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleanRequest) Reset()         { *m = CleanRequest{} }
func (m *CleanRequest) String() string { return proto.CompactTextString(m) }
func (*CleanRequest) ProtoMessage()    {}
func (*CleanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{10}
}

func (m *CleanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleanRequest.Unmarshal(m, b)
}
func (m *CleanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleanRequest.Marshal(b, m, deterministic)
}
func (m *CleanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleanRequest.Merge(m, src)
}
func (m *CleanRequest) XXX_Size() int {
	return xxx_messageInfo_CleanRequest.Size(m)
}
func (m *CleanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CleanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CleanRequest proto.InternalMessageInfo

func (m *CleanRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CleanResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleanResponse) Reset()         { *m = CleanResponse{} }
func (m *CleanResponse) String() string { return proto.CompactTextString(m) }
func (*CleanResponse) ProtoMessage()    {}
func (*CleanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{11}
}

func (m *CleanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleanResponse.Unmarshal(m, b)
}
func (m *CleanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleanResponse.Marshal(b, m, deterministic)
}
func (m *CleanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleanResponse.Merge(m, src)
}
func (m *CleanResponse) XXX_Size() int {
	return xxx_messageInfo_CleanResponse.Size(m)
}
func (m *CleanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CleanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CleanResponse proto.InternalMessageInfo

func (m *CleanResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

type UidLogoutRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UidLogoutRequest) Reset()         { *m = UidLogoutRequest{} }
func (m *UidLogoutRequest) String() string { return proto.CompactTextString(m) }
func (*UidLogoutRequest) ProtoMessage()    {}
func (*UidLogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{12}
}

func (m *UidLogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UidLogoutRequest.Unmarshal(m, b)
}
func (m *UidLogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UidLogoutRequest.Marshal(b, m, deterministic)
}
func (m *UidLogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UidLogoutRequest.Merge(m, src)
}
func (m *UidLogoutRequest) XXX_Size() int {
	return xxx_messageInfo_UidLogoutRequest.Size(m)
}
func (m *UidLogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UidLogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UidLogoutRequest proto.InternalMessageInfo

func (m *UidLogoutRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UidLogoutResponse struct {
	ResponseCode         int32    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UidLogoutResponse) Reset()         { *m = UidLogoutResponse{} }
func (m *UidLogoutResponse) String() string { return proto.CompactTextString(m) }
func (*UidLogoutResponse) ProtoMessage()    {}
func (*UidLogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{13}
}

func (m *UidLogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UidLogoutResponse.Unmarshal(m, b)
}
func (m *UidLogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UidLogoutResponse.Marshal(b, m, deterministic)
}
func (m *UidLogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UidLogoutResponse.Merge(m, src)
}
func (m *UidLogoutResponse) XXX_Size() int {
	return xxx_messageInfo_UidLogoutResponse.Size(m)
}
func (m *UidLogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UidLogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UidLogoutResponse proto.InternalMessageInfo

func (m *UidLogoutResponse) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

type CertRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertRequest) Reset()         { *m = CertRequest{} }
func (m *CertRequest) String() string { return proto.CompactTextString(m) }
func (*CertRequest) ProtoMessage()    {}
func (*CertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{14}
}

func (m *CertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertRequest.Unmarshal(m, b)
}
func (m *CertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertRequest.Marshal(b, m, deterministic)
}
func (m *CertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertRequest.Merge(m, src)
}
func (m *CertRequest) XXX_Size() int {
	return xxx_messageInfo_CertRequest.Size(m)
}
func (m *CertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CertRequest proto.InternalMessageInfo

type CertEntry struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertEntry) Reset()         { *m = CertEntry{} }
func (m *CertEntry) String() string { return proto.CompactTextString(m) }
func (*CertEntry) ProtoMessage()    {}
func (*CertEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{15}
}

func (m *CertEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertEntry.Unmarshal(m, b)
}
func (m *CertEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertEntry.Marshal(b, m, deterministic)
}
func (m *CertEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertEntry.Merge(m, src)
}
func (m *CertEntry) XXX_Size() int {
	return xxx_messageInfo_CertEntry.Size(m)
}
func (m *CertEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CertEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CertEntry proto.InternalMessageInfo

func (m *CertEntry) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CommonQueryRequest struct {
	Req                  string   `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonQueryRequest) Reset()         { *m = CommonQueryRequest{} }
func (m *CommonQueryRequest) String() string { return proto.CompactTextString(m) }
func (*CommonQueryRequest) ProtoMessage()    {}
func (*CommonQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{16}
}

func (m *CommonQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonQueryRequest.Unmarshal(m, b)
}
func (m *CommonQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonQueryRequest.Marshal(b, m, deterministic)
}
func (m *CommonQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonQueryRequest.Merge(m, src)
}
func (m *CommonQueryRequest) XXX_Size() int {
	return xxx_messageInfo_CommonQueryRequest.Size(m)
}
func (m *CommonQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommonQueryRequest proto.InternalMessageInfo

func (m *CommonQueryRequest) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

type CommonQueryResponse struct {
	Resp                 string   `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonQueryResponse) Reset()         { *m = CommonQueryResponse{} }
func (m *CommonQueryResponse) String() string { return proto.CompactTextString(m) }
func (*CommonQueryResponse) ProtoMessage()    {}
func (*CommonQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{17}
}

func (m *CommonQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonQueryResponse.Unmarshal(m, b)
}
func (m *CommonQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonQueryResponse.Marshal(b, m, deterministic)
}
func (m *CommonQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonQueryResponse.Merge(m, src)
}
func (m *CommonQueryResponse) XXX_Size() int {
	return xxx_messageInfo_CommonQueryResponse.Size(m)
}
func (m *CommonQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonQueryResponse proto.InternalMessageInfo

func (m *CommonQueryResponse) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

type CommonQueryListResponse struct {
	Resp                 []string `protobuf:"bytes,1,rep,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonQueryListResponse) Reset()         { *m = CommonQueryListResponse{} }
func (m *CommonQueryListResponse) String() string { return proto.CompactTextString(m) }
func (*CommonQueryListResponse) ProtoMessage()    {}
func (*CommonQueryListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{18}
}

func (m *CommonQueryListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonQueryListResponse.Unmarshal(m, b)
}
func (m *CommonQueryListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonQueryListResponse.Marshal(b, m, deterministic)
}
func (m *CommonQueryListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonQueryListResponse.Merge(m, src)
}
func (m *CommonQueryListResponse) XXX_Size() int {
	return xxx_messageInfo_CommonQueryListResponse.Size(m)
}
func (m *CommonQueryListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonQueryListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonQueryListResponse proto.InternalMessageInfo

func (m *CommonQueryListResponse) GetResp() []string {
	if m != nil {
		return m.Resp
	}
	return nil
}

func init() {
	proto.RegisterEnum("HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*HealthCheckRequest)(nil), "HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "HealthCheckResponse")
	proto.RegisterType((*UploadRequest)(nil), "UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "UploadResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "LogoutResponse")
	proto.RegisterType((*CleanRequest)(nil), "CleanRequest")
	proto.RegisterType((*CleanResponse)(nil), "CleanResponse")
	proto.RegisterType((*UidLogoutRequest)(nil), "UidLogoutRequest")
	proto.RegisterType((*UidLogoutResponse)(nil), "UidLogoutResponse")
	proto.RegisterType((*CertRequest)(nil), "CertRequest")
	proto.RegisterType((*CertEntry)(nil), "CertEntry")
	proto.RegisterType((*CommonQueryRequest)(nil), "CommonQueryRequest")
	proto.RegisterType((*CommonQueryResponse)(nil), "CommonQueryResponse")
	proto.RegisterType((*CommonQueryListResponse)(nil), "CommonQueryListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/SearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, "/SearchService/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/SearchService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/SearchService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Upload(context.Context, *UploadRequest) (*UploadResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SearchService/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Upload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SearchService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SearchService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
		{
			MethodName: "Upload",
			Handler:    _SearchService_Upload_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _SearchService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _SearchService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

// ProxyControllerClient is the client API for ProxyController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyControllerClient interface {
	CleanUidCache(ctx context.Context, in *CleanRequest, opts ...grpc.CallOption) (*CleanResponse, error)
}

type proxyControllerClient struct {
	cc *grpc.ClientConn
}

func NewProxyControllerClient(cc *grpc.ClientConn) ProxyControllerClient {
	return &proxyControllerClient{cc}
}

func (c *proxyControllerClient) CleanUidCache(ctx context.Context, in *CleanRequest, opts ...grpc.CallOption) (*CleanResponse, error) {
	out := new(CleanResponse)
	err := c.cc.Invoke(ctx, "/ProxyController/CleanUidCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyControllerServer is the server API for ProxyController service.
type ProxyControllerServer interface {
	CleanUidCache(context.Context, *CleanRequest) (*CleanResponse, error)
}

func RegisterProxyControllerServer(s *grpc.Server, srv ProxyControllerServer) {
	s.RegisterService(&_ProxyController_serviceDesc, srv)
}

func _ProxyController_CleanUidCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyControllerServer).CleanUidCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProxyController/CleanUidCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyControllerServer).CleanUidCache(ctx, req.(*CleanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProxyController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ProxyController",
	HandlerType: (*ProxyControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CleanUidCache",
			Handler:    _ProxyController_CleanUidCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

// ServerControllerClient is the client API for ServerController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerControllerClient interface {
	UidLogout(ctx context.Context, in *UidLogoutRequest, opts ...grpc.CallOption) (*UidLogoutResponse, error)
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type serverControllerClient struct {
	cc *grpc.ClientConn
}

func NewServerControllerClient(cc *grpc.ClientConn) ServerControllerClient {
	return &serverControllerClient{cc}
}

func (c *serverControllerClient) UidLogout(ctx context.Context, in *UidLogoutRequest, opts ...grpc.CallOption) (*UidLogoutResponse, error) {
	out := new(UidLogoutResponse)
	err := c.cc.Invoke(ctx, "/ServerController/UidLogout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverControllerClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/ServerController/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerControllerServer is the server API for ServerController service.
type ServerControllerServer interface {
	UidLogout(context.Context, *UidLogoutRequest) (*UidLogoutResponse, error)
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

func RegisterServerControllerServer(s *grpc.Server, srv ServerControllerServer) {
	s.RegisterService(&_ServerController_serviceDesc, srv)
}

func _ServerController_UidLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerControllerServer).UidLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServerController/UidLogout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerControllerServer).UidLogout(ctx, req.(*UidLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerController_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerControllerServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServerController/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerControllerServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ServerController",
	HandlerType: (*ServerControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UidLogout",
			Handler:    _ServerController_UidLogout_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _ServerController_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

// CertServiceClient is the client API for CertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CertServiceClient interface {
	Cert(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertEntry, error)
}

type certServiceClient struct {
	cc *grpc.ClientConn
}

func NewCertServiceClient(cc *grpc.ClientConn) CertServiceClient {
	return &certServiceClient{cc}
}

func (c *certServiceClient) Cert(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertEntry, error) {
	out := new(CertEntry)
	err := c.cc.Invoke(ctx, "/CertService/Cert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertServiceServer is the server API for CertService service.
type CertServiceServer interface {
	Cert(context.Context, *CertRequest) (*CertEntry, error)
}

func RegisterCertServiceServer(s *grpc.Server, srv CertServiceServer) {
	s.RegisterService(&_CertService_serviceDesc, srv)
}

func _CertService_Cert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertServiceServer).Cert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CertService/Cert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertServiceServer).Cert(ctx, req.(*CertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CertService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CertService",
	HandlerType: (*CertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cert",
			Handler:    _CertService_Cert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

// DashServiceClient is the client API for DashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DashServiceClient interface {
	ClientUid(ctx context.Context, in *CommonQueryRequest, opts ...grpc.CallOption) (*CommonQueryResponse, error)
	UidState(ctx context.Context, in *CommonQueryRequest, opts ...grpc.CallOption) (*CommonQueryResponse, error)
	UidEndpoint(ctx context.Context, in *CommonQueryRequest, opts ...grpc.CallOption) (*CommonQueryResponse, error)
	UidClients(ctx context.Context, in *CommonQueryRequest, opts ...grpc.CallOption) (*CommonQueryListResponse, error)
}

type dashServiceClient struct {
	cc *grpc.ClientConn
}

func NewDashServiceClient(cc *grpc.ClientConn) DashServiceClient {
	return &dashServiceClient{cc}
}

func (c *dashServiceClient) ClientUid(ctx context.Context, in *CommonQueryRequest, opts ...grpc.CallOption) (*CommonQueryResponse, error) {
	out := new(CommonQueryResponse)
	err := c.cc.Invoke(ctx, "/DashService/ClientUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashServiceClient) UidState(ctx context.Context, in *CommonQueryRequest, opts ...grpc.CallOption) (*CommonQueryResponse, error) {
	out := new(CommonQueryResponse)
	err := c.cc.Invoke(ctx, "/DashService/UidState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashServiceClient) UidEndpoint(ctx context.Context, in *CommonQueryRequest, opts ...grpc.CallOption) (*CommonQueryResponse, error) {
	out := new(CommonQueryResponse)
	err := c.cc.Invoke(ctx, "/DashService/UidEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashServiceClient) UidClients(ctx context.Context, in *CommonQueryRequest, opts ...grpc.CallOption) (*CommonQueryListResponse, error) {
	out := new(CommonQueryListResponse)
	err := c.cc.Invoke(ctx, "/DashService/UidClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashServiceServer is the server API for DashService service.
type DashServiceServer interface {
	ClientUid(context.Context, *CommonQueryRequest) (*CommonQueryResponse, error)
	UidState(context.Context, *CommonQueryRequest) (*CommonQueryResponse, error)
	UidEndpoint(context.Context, *CommonQueryRequest) (*CommonQueryResponse, error)
	UidClients(context.Context, *CommonQueryRequest) (*CommonQueryListResponse, error)
}

func RegisterDashServiceServer(s *grpc.Server, srv DashServiceServer) {
	s.RegisterService(&_DashService_serviceDesc, srv)
}

func _DashService_ClientUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashServiceServer).ClientUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DashService/ClientUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashServiceServer).ClientUid(ctx, req.(*CommonQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashService_UidState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashServiceServer).UidState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DashService/UidState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashServiceServer).UidState(ctx, req.(*CommonQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashService_UidEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashServiceServer).UidEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DashService/UidEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashServiceServer).UidEndpoint(ctx, req.(*CommonQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashService_UidClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashServiceServer).UidClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DashService/UidClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashServiceServer).UidClients(ctx, req.(*CommonQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DashService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DashService",
	HandlerType: (*DashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientUid",
			Handler:    _DashService_ClientUid_Handler,
		},
		{
			MethodName: "UidState",
			Handler:    _DashService_UidState_Handler,
		},
		{
			MethodName: "UidEndpoint",
			Handler:    _DashService_UidEndpoint_Handler,
		},
		{
			MethodName: "UidClients",
			Handler:    _DashService_UidClients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0xfe, 0xa5, 0x5d, 0xbb, 0xf5, 0xf4, 0xef, 0xdc, 0xe9, 0x47, 0x95, 0xab, 0xca, 0x82, 0x89,
	0x5e, 0x60, 0xa4, 0x8c, 0x7f, 0xda, 0xae, 0xa6, 0x30, 0xc1, 0xc4, 0xe8, 0x46, 0x4b, 0xc6, 0x25,
	0x0a, 0x8d, 0xd5, 0x5a, 0xcb, 0xe2, 0xce, 0x71, 0x81, 0xf1, 0x0e, 0xbc, 0x0f, 0xef, 0xc5, 0x0b,
	0xa0, 0x38, 0x76, 0x9b, 0xac, 0xad, 0x58, 0xb9, 0xa9, 0x7a, 0x4e, 0xbe, 0x73, 0xfc, 0x7d, 0xc7,
	0x9f, 0x6d, 0xa8, 0x4e, 0x05, 0x97, 0x9c, 0xa8, 0x5f, 0x4c, 0x00, 0xbd, 0xa5, 0x7e, 0x28, 0x27,
	0xee, 0x84, 0x8e, 0xae, 0x06, 0xf4, 0x66, 0x46, 0x63, 0x89, 0x3a, 0xb0, 0x1d, 0x53, 0xf1, 0x95,
	0x8d, 0x68, 0xc7, 0xea, 0x5a, 0x8f, 0x2b, 0x03, 0x13, 0xe2, 0x9f, 0x16, 0xb4, 0x73, 0x05, 0xf1,
	0x94, 0x47, 0x31, 0x45, 0x87, 0x50, 0x8e, 0xa5, 0x2f, 0x67, 0xb1, 0x2a, 0x68, 0x38, 0x98, 0xac,
	0x40, 0x91, 0x61, 0xd2, 0x25, 0x1a, 0x0f, 0x15, 0x72, 0xa0, 0x2b, 0xf0, 0x21, 0xd4, 0x73, 0x1f,
	0x50, 0x15, 0xb6, 0xbd, 0xfe, 0xbb, 0xfe, 0xf9, 0xa7, 0x7e, 0xeb, 0xbf, 0x24, 0x18, 0x9e, 0x0c,
	0x2e, 0x4f, 0xfb, 0x6f, 0x5a, 0x16, 0x6a, 0x42, 0xb5, 0x7f, 0xfe, 0xf1, 0xb3, 0x49, 0x14, 0x30,
	0x83, 0xba, 0x37, 0x0d, 0xb9, 0x1f, 0x18, 0xea, 0x2d, 0x28, 0xce, 0x58, 0xa0, 0x69, 0x27, 0x7f,
	0xd1, 0xff, 0x50, 0x16, 0x74, 0xc4, 0x45, 0xd0, 0x29, 0xa8, 0xa4, 0x8e, 0xd0, 0x1e, 0x94, 0x24,
	0xbf, 0xa2, 0x51, 0xa7, 0xa8, 0xd2, 0x69, 0x90, 0x48, 0x1f, 0x85, 0xec, 0x38, 0x08, 0x44, 0x67,
	0x2b, 0x95, 0xae, 0x43, 0x7c, 0x01, 0x0d, 0xb3, 0x94, 0x16, 0x6d, 0xc3, 0x0e, 0x15, 0x82, 0x8b,
	0xf7, 0xf1, 0x58, 0x2f, 0x38, 0x8f, 0x11, 0x86, 0x9a, 0xd0, 0x38, 0x97, 0x07, 0x54, 0xad, 0x5d,
	0x1a, 0xe4, 0x72, 0x78, 0x96, 0x08, 0xf7, 0xc5, 0x68, 0xb2, 0x9e, 0x3c, 0x86, 0x5a, 0xac, 0x20,
	0x43, 0x29, 0x58, 0x34, 0xd6, 0x12, 0x72, 0xb9, 0x7f, 0x11, 0x62, 0x96, 0x5d, 0x08, 0x31, 0xc4,
	0x3a, 0x56, 0xb7, 0x98, 0x08, 0x31, 0xf1, 0xbd, 0x84, 0x5c, 0x42, 0xed, 0x8c, 0x8f, 0x59, 0xb4,
	0x5e, 0x87, 0x0d, 0x3b, 0x53, 0x3f, 0x8e, 0xbf, 0x2d, 0xb6, 0x61, 0x1e, 0x67, 0x99, 0x16, 0xf3,
	0x4c, 0x4f, 0xa1, 0xae, 0xfb, 0xae, 0x21, 0x63, 0x2d, 0x93, 0x59, 0x8c, 0xa3, 0x90, 0x19, 0x07,
	0x3e, 0x52, 0xad, 0xf8, 0x4c, 0xae, 0xe7, 0x98, 0xe1, 0x51, 0xc8, 0xf3, 0x78, 0x06, 0x0d, 0x53,
	0x7c, 0x7f, 0x22, 0xb8, 0x0b, 0x35, 0x37, 0xa4, 0xfe, 0xfa, 0xa9, 0xe0, 0x03, 0xa8, 0x6b, 0xc4,
	0x06, 0x6d, 0x1f, 0x42, 0xcb, 0x63, 0xc1, 0x5f, 0xc4, 0xe0, 0x97, 0xb0, 0x9b, 0x41, 0x6d, 0xd0,
	0xbe, 0x0e, 0x55, 0x97, 0x0a, 0xd3, 0x19, 0x3f, 0x82, 0x4a, 0x12, 0x9e, 0x44, 0x52, 0xdc, 0xaa,
	0x09, 0xf1, 0x48, 0xd2, 0x48, 0x9a, 0x7b, 0x41, 0x87, 0x78, 0x1f, 0x90, 0xcb, 0xaf, 0xaf, 0x79,
	0xf4, 0x61, 0x46, 0xc5, 0x6d, 0x86, 0x96, 0xa0, 0x37, 0x86, 0x96, 0xa0, 0x37, 0xb8, 0x07, 0xed,
	0x1c, 0x4e, 0x13, 0x43, 0xb0, 0x95, 0x90, 0xd0, 0x48, 0xf5, 0x1f, 0x3f, 0x81, 0x07, 0x19, 0xe8,
	0x19, 0x8b, 0xe5, 0x0a, 0x78, 0xd1, 0xc0, 0x9d, 0x5f, 0x96, 0x39, 0x4d, 0xc3, 0xf4, 0xae, 0x42,
	0x3d, 0x28, 0xa7, 0x09, 0xd4, 0x20, 0xb9, 0x73, 0x66, 0x37, 0xc9, 0x9d, 0x03, 0xd0, 0x83, 0x72,
	0x7a, 0xb6, 0x51, 0x83, 0xe4, 0xee, 0x13, 0xbb, 0x49, 0xee, 0x1c, 0xfa, 0x7d, 0x28, 0x29, 0x4f,
	0xa2, 0x3a, 0xc9, 0x7a, 0xde, 0x6e, 0x90, 0xbc, 0x55, 0x7b, 0x50, 0x4e, 0xa7, 0x8f, 0xd4, 0x97,
	0xc5, 0x66, 0xd9, 0x4d, 0x92, 0xdf, 0x16, 0xe7, 0x18, 0x9a, 0x17, 0x82, 0x7f, 0xbf, 0x75, 0x79,
	0x24, 0x05, 0x0f, 0x43, 0x2a, 0x10, 0xd1, 0xce, 0xf0, 0x58, 0xe0, 0xfa, 0xa3, 0x09, 0x45, 0x75,
	0x92, 0xf5, 0x92, 0xdd, 0x20, 0x39, 0xe3, 0x38, 0x3f, 0xa0, 0x95, 0xc8, 0xa6, 0x22, 0xd3, 0xc3,
	0x81, 0xca, 0xdc, 0x02, 0x68, 0x97, 0xdc, 0x35, 0x8d, 0x8d, 0xc8, 0xb2, 0x43, 0x1c, 0x28, 0xa9,
	0x2b, 0x1b, 0xb5, 0xc9, 0xf2, 0xbb, 0x60, 0xef, 0xad, 0xba, 0xd5, 0x9d, 0xa7, 0xa9, 0x63, 0xcc,
	0xd8, 0xbb, 0xb0, 0x95, 0x84, 0xa8, 0x46, 0x32, 0x3e, 0xb2, 0x81, 0xcc, 0x6d, 0xe4, 0xfc, 0xb6,
	0xa0, 0xfa, 0xda, 0x8f, 0xe7, 0x1b, 0xf5, 0x02, 0x2a, 0x6e, 0xc8, 0x68, 0x24, 0x3d, 0x16, 0xa0,
	0x36, 0x59, 0x36, 0x92, 0xbd, 0x47, 0x56, 0xb9, 0xe6, 0x39, 0xec, 0x78, 0x2c, 0x48, 0x1e, 0x0d,
	0xba, 0x49, 0xd9, 0x2b, 0xa8, 0x7a, 0x2c, 0x38, 0x89, 0x82, 0x29, 0x67, 0x91, 0xdc, 0xa4, 0xf2,
	0x08, 0x20, 0xd9, 0x10, 0xc5, 0x35, 0x5e, 0x5d, 0xd8, 0x21, 0x6b, 0x4c, 0xfb, 0xa5, 0xac, 0x5e,
	0xdc, 0x83, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x4d, 0x1e, 0x7b, 0x80, 0x07, 0x00, 0x00,
}
